
# 全局配置
global:
{
    ## 服务根路径
    rootPath: /opt/paceic_ems_server,
    logPath: /main/log,
    dbPath: /main/db,
}

## 日志输出级别
## [ERROR, WARN, INFO, DEBUG]
logger:
[
    { name: MQServer, priority: DEBUG },
    { name: ProxyBau, priority: DEBUG },
    { name: ProxyPcs, priority: DEBUG },
    { name: CollectorBau, priority: DEBUG },
    { name: CollectorPcs, priority: DEBUG },
    { name: Interface, priority: DEBUG },
    { name: Xftg, priority: DEBUG },
    { name: Monitor, priority: DEBUG },
    { name: Station, priority: DEBUG }
]

## 从站通讯地址
slave:
[
    {
        name: BAU,
        address: 127.0.0.1:2502
    },
    {
        name: PCS,
        address: 127.0.0.1:8001
    }
]

## 注意，yaml-cpp文件末尾必须要保留空行，否则解析时会失败！！！